- hosts: all
  vars_files:
    - host_vars/setup.yaml
  gather_facts: true
  roles:
    - role: mount
    - role: dependency
    - role: docker

- hosts: couchdb
  gather_facts: true
  roles:
    - role: couchdb
    - role: python-env

- hosts: frontend
  gather_facts: true
  roles:
    - role: front

- hosts: master
  gather_facts: true
  roles:
    - role: cluster

- hosts: slave1
  gather_facts: true
  tasks:
    - name: start python twitter collector
      become: yes
      shell: docker exec python python3 TwitterCollector/main.py twitter all search

- hosts: slave2
  gather_facts: true
  tasks:
    - name: start python twitter collector
      become: yes
      shell: docker exec python python3 TwitterCollector/main.py twitter all stream

- hosts: master
  gather_facts: true
  tasks:
    - name: start python tweet2DB
      become: yes
      shell: |
        docker exec python python3 tweet/twitter2DB.py -s tweets -t twitter_data --docid loc_year_count --time 2014
        docker exec python python3 tweet/twitter2DB.py -s tweets -t twitter_data --docid loc_year_count --time 2019
        docker exec python python3 tweet/twitter2DB.py -s tweets -t twitter_data --docid loc_year_count --time 2020
        docker exec python python3 tweet/start.py


