
- name: Uninstall old versions
  become: yes
  apt:
    name: ['docker','docker-engine','docker.io','runc','containerd']
    state: absent

- name: Install Docker Engine
  become: yes
  apt:
    name: ['docker.io']
    state: present
    update_cache: yes

- name: Install Docker Compose
  become: yes
  pip:
    name: 'docker-compose'
    state: latest

- name: overwrite permission
  become: yes
  file:
    path: /var/run/docker.sock
    mode: 0666

- name: restart docker
  become: yes
  shell: systemctl start docker
#  systemd:
#    enabled: yes
#    state: restarted
#    daemon_reload: yes
#    name: docker